//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.12.18 at 02:37:44 PM IST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.learningatrmc.com/course", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package learning.spring.boot.soap.webservices.course.management.model;
